language: shell
os: linux
dist: xenial
install:
  - sudo apt-get update -y
  - sudo apt-get install python-dev libffi-dev libssl-dev -y
  - sudo apt-get install python-virtualenv lua5.1 -y
  - sudo add-apt-repository -y ppa:bartbes/love-stable
  - sudo apt-get update -y
  #- sudo apt-get install -y love=0.11.3
  - mkdir -p $TRAVIS_BUILD_DIR/share/love/
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - luarocks
before_install:
  - luarocks install --local lpeg
  - "`luarocks path`" # execute the luarocks output - sets the paths for 'local' tree
  - luarocks install busted
  - ./busted tests/busted-test.lua


script: 
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh web || ./build.sh" # web only for tags